SELECT * FROM market_star_schema.app;
SELECT * FROM market_star_schema.review_final;
-- 1.Which apps have the highest rating in the given available dataset?

Select App as largestRating_App from app
where Rating in (select Max(Rating) from app);

-- 2.What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.

select App, Rating, Reviews from app
where Rating = 5
order by Reviews desc;

-- 3.Which app has the highest number of reviews? Also, mention the number of reviews and category of the app
select App, Category,Reviews from app
where Reviews in (select Max(reviews) from app);

-- 4.	What is the total amount of revenue generated by the google play store by hosting apps? (Whenever a user buys apps  from the google play store, the amount is considered in the revenue)
select sum(Price) as Total_Revenue from app;

-- 5. Which Category of google play store apps has the highest number of installs? also, find out the total number of installs for that particular category.
select Category, sum(Installs) as Total_Installs from app
group by Category 
order by sum(Installs) desc limit 1;

-- 6. Which Genre has the most number of published apps?
select Genres, count(App) as Total_Published_App from app
group by Genres 
order by Total_Published_App desc limit 1;


-- 7. Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top
-- (to avoid duplicate results use distinct)

select App, Installs from app
where Category = 'Game'
order by Installs desc;


-- 8. Provide the list of apps that can work on android version 4.0.3 and UP
select App from app
where 'Android Ver' = '4.0.3 and up';

-- 9. How many apps from the given data set are free? Also, provide the number of paid apps.
select Type, count(App) as Total from app
group by Type;

-- 10. Which is the best dating app? (Best dating app is the one having the highest number of Reviews)
select App, Reviews from app
where Category='DATING'
order by Reviews desc limit 1;


-- 11.	Get the number of reviews having positive sentiment and number of reviews having negative 
-- sentiment for the app 10 best foods for you and compare them.

select App, Sentiment,count(Sentiment) from review_final
where App = '10 Best Foods for You'
group by Sentiment;


-- 12. Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?

select * from review_final
where App = 'ASUS SuperNote' and Sentiment_Polarity = 1 and Sentiment_Subjectivity = 1;

-- 13.	Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat 

select * from review_final
where App = 'Abs Training Burn belly fat' and Sentiment = 'Neutral';

-- 14.	Extract all negative sentiment reviews for Adobe Acrobat Reader with their 
-- sentiment polarity and sentiment subjectivity

select * from review_final
where App = 'Adobe Acrobat Reader' and Sentiment = 'Negative';


